{
	"recipes": [
		{
			"id": "explorevault_expeditionbegun",
			"label": "探險隊出發",
			"startdescription": "我已給予手下們表現的機會。希望一切順利。",
			"description": "."
		},
		{
			"id": "explorevaulttick",
			"label": "探險進行中",
			"slots": [
				{
					"id": "Assistance",
					"label": "助力",
					"description": "探險離不開資金，追隨者則能助我突破難關。"
				}
			],
			"startdescription": "我們的探險隊正準備迎接下一個挑戰，這將消耗資金。我可以追加資金，或是再派一名追隨者。",
			"description": "."
		},
		{
			"id": "explorevaultfailure_nofunds",
			"label": "後勤不力",
			"startdescription": "補給短缺。除非投入更多資金，否則我們只能放棄這次探險。",
			"description": "塵埃落定後，我們可以再試一次。"
		},
		{
			"id": "explorevaultfailure_nofollowers",
			"label": "無人歸來",
			"startdescription": "探險隊員全軍覆沒。我必須派遣幫手，否則這次探險將就此終止。",
			"description": "無人歸來。我可以再次嘗試，甚至可以沿用之前的補給。"
		},
		{
			"id": "explorevaultsuccesslink",
			"label": "寶藏近在眼前"
		},
		{
			"id": "explorevaultsuccess",
			"label": "寶藏近在眼前",
			"startdescription": "成功了！我很快就能知道更多……",
			"description": "."
		},
		{
			"id": "explorevault_casualty",
			"label": "一名探險隊員倒下了！",
			"startdescription": "我們的人手正在減少。",
			"description": "他們傷勢嚴重。[可用<b>談話</b>治療追隨者。]"
		},
		{
			"id": "explorevault_casualty_summoning",
			"label": "我的召喚物被打敗了！",
			"description": "它被放逐，或是摧毀了。"
		}
	]
}